name: ORCore
main: ORCore\ORCore
version: 1.7.2
api:
- 1.12.0
- 2.0.0
load: STARTUP
author: PocketMine Team
authors: [rewrite by AkeKy]
description: Prevents people to impersonate an account, requering registration and login when connecting.
commands:
 login:
  description: "Logs into an account"
  usage: "/login <password>"
 register:
  description: "Registers an account"
  usage: "/register <password>"
 vips:
  description: "Set Permissions"
  permission: vips.command.vips
permissions:
 orcore:
  default: op
  description: "Allows using everything ORCore has"
  children:
   orcore.chat:
    description: "Allows using the chat while not being authenticated"
    default: false
   orcore.move:
    description: "Allows moving while not being authenticated"
    default: false
   orcore.lastid:
    description: "Allows authenticating using the last id when enabled in the config"
    default: true
   orcore.command:
    description: "Allows using ORCore commands"
    default: true
 vips.command.vips:
    default: op
    description: "/vips <add/remove/list>"
